version: "3.7"

services:
  django:
    build: ./blogapi
    container_name: dev-django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./blogapi/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
  react:
    build: ./project
    container_name: dev-react
    command: npm start
    ports:
      - 3001:3000
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./project/:/srv/app
      - /srv/app/node_modules
    depends_on:
      - django

  nginx:
    build: ./nginx
    container_name: dev-nginx
    ports:
      - 8080:80
    restart: always
    volumes:
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - django
      - react
      - db

volumes:
  media:
  static:
