version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env

    command: python manage.py runserver 0.0.0.0:8000

volumes:
  dbdata:
